---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ropc-backend
  namespace: development
  labels:
    app: ropc-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ropc-backend
  template:
    metadata:
      labels:
        app: ropc-backend
    spec:
      containers:
        - name: ropc-service-container
          image: unitz007/ropc-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: ropc-db
            - name: DB_PASSWORD
              value: dbPassword
            - name: DB_USER
              value: root
            - name: DB_NAME
              value: ropc
            - name: DB_PORT
              value: "3306"
            - name: TOKEN_SECRET
              value: secretToken
            - name: TOKEN_EXPIRY
              value: "5"
            - name: GIN_MODE
              value: release
            - name: SERVER_PORT
              value: "3000"
#            - name: POD_NAME
#              valueFrom:
#                fieldRef:
#                  fieldPath: metadata.name
#            - name: POD_NAMESPACE
#              valueFrom:
#                fieldRef:
#                  fieldPath: metadata.namespace
#            - name: POD_IP
#              valueFrom:
#                fieldRef:
#                  fieldPath: status.podIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ropc-db
  namespace: development
  labels:
    app: ropc-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ropc-db
  template:
    metadata:
      labels:
        app: ropc-db
    spec:
      containers:
        - name: ropc-db-container
          image: mariadb:latest
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: dbPassword
            - name: MARIADB_DATABASE
              value: ropc
#            - name: POD_NAME
#              valueFrom:
#                fieldRef:
#                  fieldPath: metadata.name
#            - name: POD_NAMESPACE
#              valueFrom:
#                fieldRef:
#                  fieldPath: metadata.namespace
#            - name: POD_IP
#              valueFrom:
#                fieldRef:
#                  fieldPath: status.podIP